gekkoPath = '$HOME/gekko'
configFilename = 'example-config.js'
log_name = 'evolution_gen.csv'

# Hosts list of remote machines running gekko, to distribute evaluation load;
# option values: path to HOSTS file list OR False;
RemoteAWS = '../AmazonSetup/hosts'

# Your gekko local URL - CHECK THIS!
GekkoURLs = ['http://localhost:3000']
showFailedStrategies = true

